name: flutter_template_by_msi
description: A very good flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  android_id: ^0.4.0
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  device_info_plus: ^10.0.0
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  equatable: ^2.0.7
  fconnectivity: ^0.5.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.0.0
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.2
  go_router: ^14.3.0
  hydrated_bloc: ^10.0.0
  injectable: ^2.5.0
  intl: ^0.19.0
  loading_animation_widget: ^1.3.0
  nested: ^1.0.0
  package_info_plus: ^8.1.0
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0

  # Custom Dependencies
  localization:
    path: packages/localization
  app_ui:
    path: packages/app_ui
  shared:
    path: packages/shared
  storage:
    path: packages/storage/storage
  secure_storage:
    path: packages/storage/secure_storage
  persistent_storage:
    path: packages/storage/persistent_storage
  supabase_flutter: ^2.8.3
  flutter_dotenv: ^5.2.1
  lottie: ^3.3.0
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.3.5
  fpdart: ^1.1.1
  flutter_svg: ^2.0.17
  persistent_bottom_nav_bar: ^6.2.1
  dotted_border: ^2.1.0
  freezed_annotation: ^2.4.4



dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.8.0
  injectable_generator: ^2.7.0
  mocktail: ^1.0.4
  json_serializable: ^6.9.4
  mockito: ^5.4.5
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/common/
    - assets/svg/
  fonts: # TODO(msi): use your own fonts if needed
    - family: consolas
      fonts:
        - asset: assets/fonts/consolas.ttf
        - asset: assets/fonts/consolas_bold.ttf
          weight: 700
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
