name: flutter_template_by_msi
description: A very good flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  dartz: ^0.10.1
  android_id: ^0.4.0
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  device_info_plus: ^10.0.0
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  equatable: ^2.0.7
  fconnectivity: ^0.3.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.2
  go_router: ^14.3.0
  hydrated_bloc: ^9.1.5
  injectable: ^2.5.0
  intl: ^0.19.0
  loading_animation_widget: ^1.3.0
  nested: ^1.0.0
  package_info_plus: ^8.1.0
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0

  # Custom Dependencies
  localization:
    path: packages/localization
  app_ui:
    path: packages/app_ui
  shared:
    path: packages/shared
  storage:
    path: packages/storage/storage
  secure_storage:
    path: packages/storage/secure_storage
  persistent_storage:
    path: packages/storage/persistent_storage


dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  mocktail: ^1.0.4
  mockito: ^5.0.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/common/
  fonts: # TODO(msi): use your own fonts if needed
    - family: consolas
      fonts:
        - asset: assets/fonts/consolas.ttf
        - asset: assets/fonts/consolas_bold.ttf
          weight: 700
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
