arb-dir: lib/l10n
template-arb-file: app_en.arb
output-dir: lib/l10n/gen
output-class: ModuleALocalizations
output-localization-file: module_localizations.dart
synthetic-package: false
nullable-getter: false
untranslated-messages-file: untranslated_messages.json